# Generated by Django 5.1.7 on 2025-03-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('start_time', models.TimeField(verbose_name='開始時間')),
                ('end_time', models.TimeField(verbose_name='終了時間')),
                ('work_title', models.CharField(max_length=100, verbose_name='作業内容')),
                ('work_detail', models.TextField(verbose_name='作業詳細')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('boss_confirmation', models.BooleanField(default=False, verbose_name='上司確認')),
            ],
            options={
                'verbose_name': '日報',
                'verbose_name_plural': '日報',
            },
        ),
    ]
