# Generated by Django 5.1.7 on 2025-03-24 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyreport',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='work_detail',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='work_title',
        ),
        migrations.CreateModel(
            name='DailyReportDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(help_text='時:分', verbose_name='開始時間')),
                ('end_time', models.TimeField(help_text='時:分', verbose_name='終了時間')),
                ('work_title', models.CharField(max_length=100, verbose_name='作業内容')),
                ('work_detail', models.TextField(verbose_name='作業詳細')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='report.dailyreport', verbose_name='日報')),
            ],
            options={
                'verbose_name': '作業詳細',
                'verbose_name_plural': '作業詳細',
            },
        ),
    ]
