# Generated by Django 5.1.7 on 2025-03-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_remove_dailyreport_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='username',
            field=models.CharField(default='未設定', max_length=50, verbose_name='ユーザー名'),
        ),
    ]
