# Generated by Django 5.1.7 on 2025-03-24 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_alter_dailyreport_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreportdetail',
            name='remarks',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='備考'),
        ),
        migrations.AlterField(
            model_name='dailyreportdetail',
            name='work_detail',
            field=models.CharField(max_length=100, verbose_name='作業詳細'),
        ),
    ]
