# Generated by Django 5.1.7 on 2025-03-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_alter_dailyreport_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreportdetail',
            name='work_detail',
            field=models.TextField(blank=True, null=True, verbose_name='作業詳細'),
        ),
    ]
