# Generated by Django 5.1.7 on 2025-03-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_alter_dailyreportdetail_work_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreportdetail',
            name='work_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='作業内容'),
        ),
    ]
