# Generated by Django 5.1.7 on 2025-03-31 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0010_alter_dailyreportdetail_work_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyreport',
            options={'ordering': ['-date'], 'verbose_name': '日報', 'verbose_name_plural': '日報'},
        ),
        migrations.AlterModelOptions(
            name='dailyreportdetail',
            options={'ordering': ['start_time'], 'verbose_name': '作業詳細', 'verbose_name_plural': '作業詳細'},
        ),
        migrations.RemoveField(
            model_name='dailyreportdetail',
            name='remarks',
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='備考'),
        ),
        migrations.AlterField(
            model_name='dailyreportdetail',
            name='end_time',
            field=models.TimeField(verbose_name='終了時間'),
        ),
        migrations.AlterField(
            model_name='dailyreportdetail',
            name='start_time',
            field=models.TimeField(verbose_name='開始時間'),
        ),
        migrations.AlterField(
            model_name='dailyreportdetail',
            name='work_title',
            field=models.CharField(default='-', max_length=200, verbose_name='作業内容'),
            preserve_default=False,
        ),
    ]
