# Generated by Django 5.1.7 on 2025-03-31 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0011_alter_dailyreport_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreportdetail',
            name='work_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='作業内容'),
        ),
    ]
