# Generated by Django 5.1.7 on 2025-04-04 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0012_alter_dailyreportdetail_work_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='報告事項'),
        ),
    ]
