# Generated by Django 5.1.7 on 2025-04-04 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0013_dailyreport_created_at_dailyreport_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='コメント'),
        ),
    ]
