# Generated by Django 5.1.7 on 2025-04-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0014_dailyreport_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='is_submitted',
            field=models.BooleanField(default=False, verbose_name='提出'),
        ),
    ]
