# Generated by Django 5.1.7 on 2025-05-10 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0015_dailyreport_is_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreportdetail',
            name='responsible_person',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='担当者'),
        ),
    ]
