# Generated by Django 5.1.7 on 2025-05-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0016_dailyreportdetail_responsible_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreportdetail',
            name='client',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='得意先'),
        ),
    ]
