# Generated by Django 5.1.7 on 2025-07-01 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0018_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyreportdetail',
            name='work_detail',
        ),
    ]
